CREATE TABLE IF NOT EXISTS users (
	id		UUID				PRIMARY KEY,
	name		VARCHAR(32) 			NOT NULL,
	email		VARCHAR(32) 			NOT NULL,
	password	VARCHAR(64)			NOT NULL,
	salt		VARCHAR(32)			NOT NULL,
	date_registered	TIMESTAMP WITHOUT TIME ZONE	NOT NULL,
	last_login	TIMESTAMP WITHOUT TIME ZONE	NOT NULL
);

CREATE TABLE IF NOT EXISTS tokens (
	id		UUID				PRIMARY KEY,
	owner		UUID				REFERENCES users(id) NOT NULL,
	issued		TIMESTAMP WITHOUT TIME ZONE	NOT NULL
);